const countries = [
    'qatar',
    'ecuador',
    'senegal',
    'netherlands',
    'england',
    'iran',
    'usa',
    'wales',
    'argentina',
    'saudi arabia',
    'mexico',
    'poland',
    'france',
    'australia',
    'denmark',
    'tunisia',
    'spain',
    'costarica',
    'germany',
    'japan',
    'belgium',
    'canada',
    'morocco',
    'croatia',
    'brasil',
    'serbia',
    'switzerland',
    'cameroon',
    'portugal',
    'ghana',
    'uruguay',
    'south korea',
];

export default countries;